######################################################################
#
# File name : DIV_tb_compile.do
# Created on: Tue Apr 07 16:53:51 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../DIV.srcs/sources_1/new/DIV.v" \
"../../../DIV.srcs/sim_1/new/DIV_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

