######################################################################
#
# File name : cpu_tb_wave.do
# Created on: Sun May 17 19:23:02 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
