######################################################################
#
# File name : cpu_tb_compile.do
# Created on: Sun May 17 19:22:52 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/dist_mem_gen_v8_0_10
vlib msim/xil_defaultlib

vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10
vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../CPU31.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../CPU31.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../CPU31.srcs/sources_1/new/regfile.v" \
"../../../CPU31.srcs/sources_1/new/PC.v" \
"../../../CPU31.srcs/sources_1/new/inst_decoder.v" \
"../../../CPU31.srcs/sources_1/new/controller.v" \
"../../../CPU31.srcs/sources_1/new/alu.v" \
"../../../CPU31.srcs/sources_1/new/DMEM.v" \
"../../../CPU31.srcs/sources_1/new/cpu.v" \
"../../../CPU31.srcs/sources_1/new/IMEM.v" \
"../../../CPU31.srcs/sources_1/new/sccomp_dataflow.v" \
"../../../CPU31.srcs/sim_1/new/cpu_tb.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

