######################################################################
#
# File name : DIVU_tb_simulate.do
# Created on: Tue Apr 07 16:20:03 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.DIVU_tb xil_defaultlib.glbl

do {DIVU_tb_wave.do}

view wave
view structure
view signals

do {DIVU_tb.udo}

run 1000ns
