######################################################################
#
# File name : DIVU_tb_compile.do
# Created on: Tue Apr 07 16:19:50 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../DIVU.srcs/sources_1/new/DIVU.v" \
"../../../DIVU.srcs/sim_1/new/DIVU_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

