######################################################################
#
# File name : _246tb_ex10_tb_wave.do
# Created on: Tue Aug 04 17:11:45 +0800 2026
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
