######################################################################
#
# File name : _246tb_ex10_tb_simulate.do
# Created on: Mon Sep 14 17:00:46 +0800 2026
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_r/0 +pulse_int_r/0 -L simprims_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib._246tb_ex10_tb xil_defaultlib.glbl

do {_246tb_ex10_tb_wave.do}

view wave
view structure
view signals

do {_246tb_ex10_tb.udo}

run 1000ns
