######################################################################
#
# File name : _246tb_ex10_tb_wave.do
# Created on: Mon Sep 14 17:00:46 +0800 2026
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
