######################################################################
#
# File name : _246tb_ex10_tb_compile.do
# Created on: Tue Aug 04 17:11:40 +0800 2026
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"_246tb_ex10_tb_time_synth.v" \
"../../../../CPU54.srcs/sim_1/new/testbench_cpu54_single.v" \


quit -force

