######################################################################
#
# File name : _246tb_ex10_tb_wave.do
# Created on: Sat Sep 12 23:11:48 +0800 2026
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
