######################################################################
#
# File name : MULT_tb_compile.do
# Created on: Thu Apr 02 15:07:54 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../MULT.srcs/sources_1/new/MULT.v" \
"../../../MULT.srcs/sim_1/new/MULT_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

