######################################################################
#
# File name : MULT_tb_wave.do
# Created on: Thu Apr 02 15:08:00 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
