######################################################################
#
# File name : DIVU_tb_wave.do
# Created on: Tue Apr 07 16:20:03 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
