######################################################################
#
# File name : MULTU_tb_compile.do
# Created on: Thu Apr 02 14:48:51 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../MULTU.srcs/sources_1/new/MULTU.v" \
"../../../MULTU.srcs/sim_1/new/MULTU_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

