######################################################################
#
# File name : MULTU_tb_wave.do
# Created on: Thu Apr 02 14:48:57 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
