######################################################################
#
# File name : cpu_tb_compile.do
# Created on: Mon May 18 19:51:27 +0800 2026
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"cpu_tb_time_synth.v" \
"../../../../CPU31.srcs/sources_1/new/regfile.v" \
"../../../../CPU31.srcs/sources_1/new/PC.v" \
"../../../../CPU31.srcs/sources_1/new/inst_decoder.v" \
"../../../../CPU31.srcs/sources_1/new/controller.v" \
"../../../../CPU31.srcs/sources_1/new/alu.v" \
"../../../../CPU31.srcs/sources_1/new/DMEM.v" \
"../../../../CPU31.srcs/sources_1/new/cpu.v" \
"../../../../CPU31.srcs/sources_1/new/IMEM.v" \
"../../../../CPU31.srcs/sources_1/new/sccomp_dataflow.v" \
"../../../../CPU31.srcs/sim_1/new/cpu_tb.v" \


quit -force

