######################################################################
#
# File name : cpu_tb_wave.do
# Created on: Mon May 18 19:51:38 +0800 2026
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
