# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.cache/wt [current_project]
set_property parent.project_path D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files c:/Users/14714/OneDrive/Resources/Tongji-CS-2026-spring-my-archive/计算机组成原理/materials/31条指令CPU实验相关文档/31条CPUcoe文件/mips_31_mars_simulate.coe
add_files c:/Users/14714/OneDrive/Resources/Tongji-CS-2026-spring-my-archive/计算机组成原理/materials/31条指令CPU实验相关文档/31条CPUcoe文件/mips_31_mars_board_switch.coe
add_files -quiet D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/new/regfile.v
  D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/new/PC.v
  D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/new/inst_decoder.v
  D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/new/controller.v
  D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/new/alu.v
  D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/new/DMEM.v
  D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/new/cpu.v
  D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/new/IMEM.v
  D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/new/seg7x16.v
  D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/new/sccomp_dataflow.v
  D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/sources_1/new/sccomp_board.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/constrs_1/new/icf.xdc
set_property used_in_implementation false [get_files D:/Xilinx/Vivado_projects/CPU31/CPU31/CPU31.srcs/constrs_1/new/icf.xdc]


synth_design -top sccomp_board -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_board.dcp

catch { report_utilization -file sccomp_board_utilization_synth.rpt -pb sccomp_board_utilization_synth.pb }
