######################################################################
#
# File name : _246tb_ex10_tb_wave.do
# Created on: Tue Aug 04 13:49:59 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
