######################################################################
#
# File name : _246tb_ex10_tb_compile.do
# Created on: Tue Aug 04 13:49:54 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/dist_mem_gen_v8_0_10
vlib msim/xil_defaultlib

vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10
vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../CPU54.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../CPU54.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../CPU54.srcs/sources_1/new/MUL.v" \
"../../../CPU54.srcs/sources_1/new/HI_LO.v" \
"../../../CPU54.srcs/sources_1/new/DIV.v" \
"../../../CPU54.srcs/sources_1/new/CP0.v" \
"../../../CPU54.srcs/sources_1/new/CLZ.v" \
"../../../CPU54.srcs/sources_1/new/regfile.v" \
"../../../CPU54.srcs/sources_1/new/PC.v" \
"../../../CPU54.srcs/sources_1/new/inst_decoder.v" \
"../../../CPU54.srcs/sources_1/new/controller.v" \
"../../../CPU54.srcs/sources_1/new/alu.v" \
"../../../CPU54.srcs/sources_1/new/IMEM.v" \
"../../../CPU54.srcs/sources_1/new/DMEM.v" \
"../../../CPU54.srcs/sources_1/new/cpu.v" \
"../../../CPU54.srcs/sources_1/new/sccomp_dataflow.v" \
"../../../CPU54.srcs/sim_1/new/testbench_cpu54_single.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

